title: "JMP-INT3RN415"
description: "A Journal and a Blog for breaking things until i get a shell "
author:
  name: "On3manarmy"
  email: "aarassen@gmail.com"
  url: "https://aarassen.github.io/"

baseurl: /jmp-int3RN415/

source: ./jmp-int3RN415/
destination: ./jmp-int3RN415/_site
permalink: /jmp-int3RN415/:title
paginate: 3
paginate_path: /jmp-int3RN415/page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "On3manarmy"
year : "2022"
